FROM sima-build-py34

MAINTAINER Jeff Zaremba <jzaremba@gmail.com>

RUN apt-get update -qq && apt-get install -qq \
    python-qwt5-qt4 \
    python-sip \
    python-qt4 \
    && apt-get clean

RUN rm -r /usr/lib/python2.7/dist-packages/numpy*

RUN pip install guidata

RUN pip install guiqwt

RUN mkdir /code
WORKDIR /code

COPY roibuddy_build_script.sh .

CMD bash
