FROM python:2.7

MAINTAINER Jeff Zaremba <jzaremba@gmail.com>

RUN apt-get update -qq && apt-get install -qq python-dev libatlas-dev libatlas-base-dev liblapack-dev libgeos-dev libhdf5-dev

RUN pip install Cython

RUN pip install numpy

RUN pip install scipy scikit-image scikit-learn shapely pillow future h5py picos twine

RUN mkdir /code
WORKDIR /code

COPY sima_build_script.sh .

CMD bash
